spring:
  application:
    name: RandomApiByAlist

  data:
    redis:
      host: 10.10.1.1
      port: 6379
      database: 0
      timeout: 1800000 # 使用毫秒格式，兼容 Redis Lettuce
      password: Alone117
      lettuce:
        pool:
          max-active: 20  # 最大连接数
          max-wait: -1    # 最大阻塞等待时间(负数表示无限制)
          max-idle: 5     # 最大空闲连接数
          min-idle: 0     # 最小空闲连接数

alist:
  dirs: /HLP/Blog/OSSImage
  targetUrl: https://davidhlp.asia
  redirectUrl: https://davidhlp.asia/d
  getTokenApi: /api/auth/login
  getDirDocument: /api/fs/list
  username: DavidHLP
  password: "#Alone117"
  Host: davidhlp.asia
  queue:
    delay: 10 # 队列处理的延迟时间（毫秒）
    size: 10

server:
  port: 12000

logging:
  level:
    root: INFO # 全局日志级别
    org.springframework: DEBUG # Spring 框架调试日志级别
    org.springframework.boot.autoconfigure: OFF # 禁用自动配置日志
  file:
    name: /opt/logs/RandomApiByAlist.log # 指定日志文件路径
