spring:
  application:
    name: RandomApiByAlist

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 1800000 # 使用毫秒格式，兼容 Redis Lettuce
      password: Alone117
      lettuce:
        pool:
          max-active: 20  # 最大连接数
          max-wait: -1    # 最大阻塞等待时间(负数表示无限制)
          max-idle: 5     # 最大空闲连接数
          min-idle: 0     # 最小空闲连接数

alist:
  dirs: /xxx/xx,/xxx/xxx # 支持多个目录
  targetUrl: https://your-alist-host # alist的url
  redirectUrl: https://your-alist-host/d # d是一个直链表达
  getTokenApi: /api/auth/login # V3 alist 的 API 登录的
  getDirDocument: /api/fs/list # V3 alist 的 API 获取目录下内容
  username: your-alist-username
  password: your-alist-password
  Host: your-alist-host
  queue:
    delay: 10 # 队列处理的延迟时间（毫秒）
    size: 10

server:
  port: 12000

logging:
  level:
    root: INFO # 全局日志级别
    org.springframework: DEBUG # Spring 框架调试日志级别
    org.springframework.boot.autoconfigure: OFF # 禁用自动配置日志
  file:
    name: /opt/logs/RandomApiByAlist.log # 指定日志文件路径
